# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target :'DoubleBasicHelloWorld' do
    pod 'AWSCore'
    #pod 'AWSAutoScaling'
    #pod 'AWSCloudWatch'
    pod 'AWSCognito'
    pod 'AWSCognitoIdentityProvider'
    #pod 'AWSDynamoDB'
    #pod 'AWSEC2'
    #pod 'AWSElasticLoadBalancing'
    pod 'AWSIoT'
    #pod 'AWSKinesis'
    pod 'AWSLambda'
    #pod 'AWSMachineLearning'
    #pod 'AWSMobileAnalytics'
    #pod 'AWSS3'
    pod 'AWSSES'
    #pod 'AWSSimpleDB'
    pod 'AWSSNS'
    pod 'AWSSQS'
end
